server:
  port: 8010 # 项目端口号
spring:
  application:
    name: alibaba-user # 项目发布名称
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动串
    url: jdbc:mysql://192.168.184.77:3306/yulanshenhai_alibaba?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8 # 连接串
    username: root # 连库账号
    password: gzy18845010667 # 连库密码
    type: com.alibaba.druid.pool.DruidDataSource # Druid连接池
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.184.77:8848 # nacos服务地址
    sentinel:
      transport:
        port: 8888 # sentinel跟控制台交流的内部端口号，随意指定一个未使用的端口即可
        dashboard: 192.168.184.77:8858 # sentinel管控台端口号

# MP配置
mybatis-plus:
  type-aliases-package: com.yulanshenhai.entity # 实体类别名包扫描
  configuration:
    map-underscore-to-camel-case: true # 下划线自动转驼峰
    cache-enabled: true # 开启二级缓存
    lazy-loading-enabled: true # 开启全局懒加载
    aggressive-lazy-loading: false # 关闭全局积极加载
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台SQL语句

# OpenFeign
feign:
  sentinel:
    enabled: true


